package org.techntravels.cart.module.config;

public enum ConfigConstant {

	CART_DISCOUNT_EMPLOYEE_PERCENTAGE("CART.DISCOUNT.EMPLOYEE.PERCENTAGE"),

	CART_DISCOUNT_AFFILIATE_PERCENTAGE("CART.DISCOUNT.AFFILIATE.PERCENTAGE"),

	CART_DISCOUNT_OLD_CUSTOMER_PERCENTAGE("CART.DISCOUNT.OLD.CUSTOMER.PERCENTAGE"),
	CART_DISCOUNT_OLD_CUSTOMER_MIN_AGE("CART.DISCOUNT.OLD.CUSTOMER.MIN.AGE"),

	CART_DISCOUNT_SALES_MINIMUM_BILL("CART.DISCOUNT.SALES.MINIMUM.BILL"),
	CART_DISCOUNT_SALES_DISCOUNT_AMOUNT("CART.DISCOUNT.SALES.DISCOUNT.AMOUNT");

	private String value;

	private ConfigConstant(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}
}
